### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by rubensworks** [Azanor/thaumcraft-5-api#1]
It looks like the API refers to classes that are not included in the API, for example:

https://github.com/Azanor/thaumcraft-5-api/blob/745f29e7d500b28565b4260c8716d6a40ffaecb2/blocks/BlocksTC.java#L3
https://github.com/Azanor/thaumcraft-5-api/blob/abb571df64598ddf47b1384a40f5cae13e7d5063/blocks/TileThaumcraft.java#L12

This makes it impossible to compile a mod using this API unless the dev build is included, which is not always possible.

**Comment by Azanor** [comment]
Oops, I will fix that
