### ISSUE TITLE
Friggin totems(of attraction), how do they work?

### ISSUE THREAD

**Issue by ghost** [Azanor/thaumcraft-5-api#16]
What I am describing is most likely the intended behaviour,
but it seems kind of counterproductive to me.
1. They don't always work even if vis is available around them, seems to be that they ignore low vis levels for safety reasons, which doesn't help at all when you are moving flux around.
2. They burn shards even if there is apparently no vis for them to draw(Okay, that kind of makes sense, but a Thaumaturge would propably want to not have this happen)
3. They have aspect orbs flying towards them even when they are not drawing any vis.

Flux management seemed like the only reasonable way to use them for me, but it seems that doesn't work at all.

If this is the wrong place to say this OKAY, but where else could I say this?

Also where should I put my reports on mistakes in the Thaumonomicon? Or is that not necessary, because that one will also be completely remade(in favor of a HQM-like system?)

**Comment by ghost** [comment]
Oh, to be more precise, the totem has no poles at all, so it should merely try to draw vitium from the 8 surrounding chunks into it's own chunk.

Needless to say, still nothing happening at all. Only eating shards.

**Comment by Azanor** [comment]
Firstly, posting this in the thaumcraft-5 github would help, not the api one.

Secondly, are you using the right shards?

Thirdly, are you doing this in the overworld? There is currently a bug where aura operations aren't happening in the correct dimensions.

**Comment by ghost** [comment]
Oh.
1. I'm sorry, I thought this was the only github. I think people keep making this mistake. I, hopefully will not make it again.
2. Tainted shards to attract taint, where could I go wrong with that?
3. Yes, on the overworld. In creative I tested the totem a bit and it seemed to work except for the fact that you can't get all the flux where you want it.

It seems there is some kind of threshold below which totems no longer work.
Is that the way it should be, even for Flux?

**Comment by Azanor** [comment]
There is no threshold - they should keep pulling as long as there is something to pull. The problem might be that a single totem is not likely to be enough depending on what is adding flux to your aura. It only does a single pull operation a few times a second. The aura updates regularly enough that stuff spreads out as fast as the aura can pull it.
Think of a puddle of mud that you are trying to scoop into a pile. It will just try and spread into a puddle again unless you scoop it fast enough.

**Comment by ghost** [comment]
Well that cannot be the problem.
1. No flux is being added to my aura, I produced some flux on purpose and very small amounts of it don't do anything, so no more flux can come.
2. On regular vis the effect is quite interesting, though. It creates a very neat spike in the aura, that flows back as soon as the totem is deactivated, like a vacuum cleaner VS a curtain.
3. Thing is, the chunk where the totem is is completely empty(no flux), the surrounding 4 chunks have a total of 20flux(5 per chunk) and the totem runs on tainted shards.
   What I do observe: Nothing! Sometimes when the totem draws vis, it produces some taint fume, it doesn't even do that right now. And I have left it like that for quite a hwile, came back and the 20flux were still there, the target chunk was still empty(Okay there was a pure node in it, so it would have been empty anyway, but not the surrounding chunks.)

Should I make a video on YT to clarify the situation?

**Comment by ghost** [comment]
Okay I have uploaded it, it's private right now, how do I whitelist you for it? Unless I should just set it to public.

**Comment by ghost** [comment]
oops

**Comment by ghost** [comment]
Nevermind. Unlisted is a thing.

https://www.youtube.com/watch?v=1g5ObGe3uhQ
