### ISSUE TITLE
Custom Infusion Enchantments

### ISSUE THREAD

**Issue by Tuhljin** [Azanor/thaumcraft-5-api#18]
With TC4, I was able to create new infusion enchantments. Maybe I'm missing something, but I don't see a way to do that now. InfusionEnchantmentRecipe is marked as deprecated.

In case it matters, I'm trying to create a recipe that applies Lure and another for Luck of the Sea. Obviously, I'd need to be able to apply them to fishing rods.

**Comment by Azanor** [comment]
Infusion enchantment has nothing to do with vanilla enchantments - they are powerful TC added enchantments. For now I will not be exposing them via the API either.
