### ISSUE TITLE
What happened to the the 4.x API repo?

### ISSUE THREAD

**Issue by IceDragon200** [Azanor/thaumcraft-5-api#2]
:sob: We had it as a submodule for [Growthcraft](https://github.com/Alatyami/Growthcraft-1.7) to avoid including the api physically.

If anything just lock issues on the repo and leave a note in a readme that a newer version is available, since this version is for Thaumcraft 5 (minecraft 1.8) and we're still on 1.7.

**Comment by rubensworks** [comment]
I second this, my CI builds are failing because of this, and I don't really want to add the TC4 api files directly to the repo.

**Comment by Azanor** [comment]
I recreated the old repository with the same name.
