### ISSUE TITLE
Broken textures on custom seal. Looking in wrong domain?

### ISSUE THREAD

**Issue by Tuhljin** [Azanor/thaumcraft-5-api#20]
I'm creating some custom control seals for golems and can place my seal in world but I haven't been able to get custom textures to work. Both the item ("item placer") and entity versions of the seal show missing/broken textures. I've double- and triple-checked that the files (PNG texture and JSON model file) are correctly in their respective places, but it appears that despite me specifying in the ResourceLocation to look in my mod's domain, the error messages indicate that Minecraft is looking in the "thaumcraft" folder.

The relevant part of the log is [here](https://gist.github.com/Tuhljin/9b020ee8bebebbd257dd). And this is probably the most relevant of _that_:

> [20:22:07] [Client thread/ERROR] [FML]: Exception loading model for variant thaumcraft:seal_craft#inventory for item "thaumcraft:seal"
> java.lang.Exception: Could not load model definition for variant thaumcraft:seal_craft#inventory
>   at net.minecraftforge.client.model.ModelLoader.getModelBlockDefinition(ModelLoader.java:215) ~[ModelLoader.class:?]
> 
> _[omitting several lines]_
> 
> Caused by: java.lang.RuntimeException: Encountered an exception when loading model definition of model thaumcraft:blockstates/seal_craft.json
>   at net.minecraft.client.resources.model.ModelBakery.getModelBlockDefinition(ModelBakery.java:165) ~[ModelBakery.class:?]
>   at net.minecraftforge.client.model.ModelLoader.getModelBlockDefinition(ModelLoader.java:211) ~[ModelLoader.class:?]
>   ... 22 more
> Caused by: java.io.FileNotFoundException: thaumcraft:blockstates/seal_craft.json
>   at net.minecraft.client.resources.FallbackResourceManager.getAllResources(FallbackResourceManager.java:93) ~[FallbackResourceManager.class:?]

(This error shows up in the log before reaching the main menu.)

As you can see, it is referring to the "thaumcraft" domain instead of my own, and of course isn't finding the JSON there because that's the wrong place. There were no references to my mod domain in the log elsewhere, either. All my textures for other items and blocks work fine.

I also noticed that the item placer itself has the domain thaumcraft as part of its ID but I had assumed that was normal due to the way the item was registered. All seals, including ones I registered, are called "thaumcraft:seal". However, now that I see this problem, maybe it is related.

My seal class includes this:

```
    public ResourceLocation icon;
    public String key;

    public SealCraft() {
        this.icon = new ResourceLocation("automagy", "items/seals/seal_craft");
        this.key = "Automagy:craft";
    }

    @Override
    public String getKey() {
        return key;
    }

    @Override
    public ResourceLocation getSealIcon() {
        return icon;
    }
```

The ResourceLocation I use is practically the same as the ones Thaumcraft itself uses for its seals except that the domain is for my mod, and the file is there, so I don't see how that could be the problem. Am I missing something?

**Comment by Azanor** [comment]
You will have to use the thaumcraft domain if I am not mistaken. The seal key can have your own domain, but the icons more than likely not. The item is registered within thaumcraft so forge will be looking for the models in that domain.

Give it a shot and see if it works. I'm not sure that there is a workaround for that.

**Comment by Tuhljin** [comment]
Alright, I put my JSON files in the thaumcraft assets folder and the textures now work. For some reason, it seemed to me that I must be doing it wrong if I didn't put them in my own domain. Thanks for your help.

_Edit: Ignore the rest. See next comment._

There is another problem, however - and maybe this should be in its own ticket. Everything seems to be fine in my dev environment, but when I build it and try to use it elsewhere (still with Thaumcraft 5.2.1), the seal doesn't show up in-game. I don't see it anywhere in the creative tabs or JEI.

And when I add a recipe for the seal, Minecraft crashes on start up because the item stack from GolemHelper.getSealStack is somehow null:

```
[...]
        addShapelessBasicRecipe(GolemHelper.getSealStack("Automagy:shear"), ItemsTC.seals, Items.shears); // basic recipe, for testing
[...]
    public static void addShapelessBasicRecipe(ItemStack stack, Object... par) {
        ShapelessOreRecipe recipe = new ShapelessOreRecipe(stack, par); // crashes here
        GameRegistry.addRecipe(recipe);
        storeRecipe(stack, recipe);
    }
```

Here's the [crash report](https://gist.github.com/Tuhljin/3828733c918891d22c9f).

Again, this isn't an issue in the dev environment, so I'm at a loss as to what the cause is.

**Comment by Tuhljin** [comment]
Never mind on the second problem. The stack wasn't null; it was actually ItemsTC.seals, which made me realize that I neglected to add the dependencies to my `@Mod` line. It worked fine in the dev environment but loaded in a different order elsewhere.

Thanks again for your help.
