### ISSUE TITLE
Request: Better control over Provision Requests

### ISSUE THREAD

**Issue by Tuhljin** [Azanor/thaumcraft-5-api#21]
This is related to a problem I reported here: https://github.com/Azanor/thaumcraft-5/issues/512 . This suggestion may not be viable unless that problem is fixed (or maybe both birds can be killed with one stone).

The problem noted there is that provision requests from golem seals are inflexible, not ignoring things like metadata even if the seals are set to do so. When that's no longer a problem, it would be even better if we could somehow specify more dynamically in our custom seals whether an item was acceptable for provisioning. We could look at the item damage and do some basic logic, for example. Ideally, we'd be able to specify an item count, too, so we can regulate the number of a given item going to an inventory.

I need something like this because I want a seal to request an item from its filter and not simply completely ignore the item damage but actually take it into the consideration so the item is accepted usually but, if a certain toggle is set, the item is rejected if it is about to break. This is done to preserve the item much like the arcane bore does. (I can and do use this logic in canGolemPerformTask, but the Provide seal doesn't check that nor should it since that method checks against a golem, not an item stack.)

Perhaps the solution could involve letting us extend the ProvisionRequest class to make our own rules.

**Comment by Azanor** [comment]
A provisioning request is always for a _specific_ item and the filters you specify on the seal itself applies to what items that seal _may_ provision and not the items drawn from the container - the item drawn will always be the exact one requested in the first place.
Having said that however, it does indeed cause a problem for damageable items like tools. I could allow all damage values for tools to slip through, but I'm not sure that is correct. I think the actual seal asking for provisioning should simply send the OreDictionary.WILDCARD_VALUE value under the correct circumstances. 
I will update my checks take that into account.

**Comment by Tuhljin** [comment]
That would definitely be better than how it is now, but would you consider enabling some way of preventing grabbing items that will be destroyed if damaged again, similar to the Arcane Bore's preservation of items (albeit those are already in a slot)? I'd really prefer to not entirely consume items due to the golem damaging them upon use unless the player opts in for it. Perhaps if the item is damageable and the wildcard value was used, it ignores those at their max damage (or max damage - 1, leaving 1 durability like the bore does).

**Comment by Azanor** [comment]
Hmmm, I feel that is a bit beyond the scope of simple inventory management seals.

**Comment by Tuhljin** [comment]
Alright, I suppose I'll see what can be done without it (I may have to make a note in my research entry to clue players in on the limitations so they can work around them) and if the workarounds feel too unintuitive, I can create an Advanced Provide seal or something. Thanks.
