### ISSUE TITLE
Tainted nodes permanently changed my view on relaity.

### ISSUE THREAD

**Issue by ghost** [Azanor/thaumcraft-5-api#3]
So I ran through the Taiga on my horse during the Night, watched a tainted node spew stuff into the air and then THIS.

![2015-11-02_20 51 49](https://cloud.githubusercontent.com/assets/11749762/10893552/aa7a936c-81a9-11e5-9910-279b1af48e8d.png)
![2015-11-02_20 53 07](https://cloud.githubusercontent.com/assets/11749762/10893556/b3cefa2a-81a9-11e5-97f1-186d509b3e4b.png)

Reloading the world didn't fix it. Reloading the entire game did.

Off-topic. What thought exactly is the foundation of taint being irreversible?
I see more issues with that than logical reasons. May I be enlightened?

**Comment by ghost** [comment]
Oh no, the typo in the title!

**Comment by Azanor** [comment]
Taint or tainted nodes don't do anything like that. Did you get a warp effect?

Also, this is the wrong place for bug reports.

**Comment by ghost** [comment]
It's not? Sorry. I didn't pay attention then.
I did have warp, but only the standard tiny amount you get from learning how to learn.
Like I said this happened immediately after I saw a tainted node puff out.
Perhaps it's an issue of LWJGL... Or the forge version... Anyway, nothing additionaly installed. Just TC5 and Baubles.

**Comment by Azanor** [comment]
I think you might have run into a very odd vanilla or forge bug. I wish I was able to alter the rendering of arms like that in MC1.8 - it would make me able to animate the wand again  :p

**Comment by ghost** [comment]
...if you are referring to that strange thing at the bottom of the screen, that's a horse.

**Comment by Azanor** [comment]
Hmmm, well apart from that all I see is minecraft at night. What exactly is the issue?

**Comment by ghost** [comment]
On the first screenshots you can see large portions of the ground being invisible with the caves showing up deep in the ground, this is also very clearly visibly on the right side of my little hill in the second screenshot.
Also if you look at the background you can see that the trees look really funky and in the second screenshot, that trippy construct in the very center of the screen is actually supposed to be a vanilla village. The wall of my house aint looking normal either.

Any surfaces seen from the side or far away seem to have this blue-stain effect.

It was not displaying any status effects and it persisted when I reloaded the world, but stopped when I reopened Minecraft.
