### ISSUE TITLE
Wand Focus: Portable Hole vis cost is broken

### ISSUE THREAD

**Issue by pedrotristain** [Azanor/thaumcraft-5-api#4]
Hey Azanor,

The W. Focus: Portable Hole cost is initially 25 Aer, Terra and Perditio. After the first cast, the cost goes up to 825 of each. After the second cast (if you can pay for the 825 cost) it goes up to 27225 of each vis.

In my private server, the hole will open on the first cast (and second cast) and work properly. It will even close as it should do. But on every single player game I started, the hole won't even open.
![tc-bug3](https://cloud.githubusercontent.com/assets/15629945/10939267/8471f23e-82e7-11e5-8301-36d68cf95837.jpg)
![tc-bug4](https://cloud.githubusercontent.com/assets/15629945/10939268/8473cf46-82e7-11e5-8a9a-dad017816410.jpg)

**Comment by Azanor** [comment]
This is the wrong place to report errors and it has been reported already so closing this.
