### ISSUE TITLE
Nodes renders oddly reguarding chests, water, and taint dust

### ISSUE THREAD

**Issue by NevermoreKnight** [Azanor/thaumcraft-5-api#5]
Nodes regardless of whether they are in front or behind a chest are rendered behind the chest. This is the same with taint dust and water.

Example with taint dust:
![2015-11-05_14 41 17](https://cloud.githubusercontent.com/assets/15677223/10979600/60865d94-83cb-11e5-96c9-567412166b83.png)

Example with Chests:
![2015-11-05_14 41 38](https://cloud.githubusercontent.com/assets/15677223/10979603/638b259c-83cb-11e5-9ddd-42b4186d1c98.png)

Example with water:
![2015-11-05_14 43 14](https://cloud.githubusercontent.com/assets/15677223/10979648/976f1c06-83cb-11e5-8baa-fcb42999bd2a.png)

**Comment by Azanor** [comment]
Firstly, this repository is not for bug reporting.
Secondly - yeah, the problem you describe is super annoying, but unfortunately it is a side effect of the way minecraft renders stuff, Not much I can do about unfortunately.
