### ISSUE TITLE
Client events for SyncResearch and ResearchComplete

### ISSUE THREAD

**Issue by mezz** [Azanor/thaumcraft-5-api#6]
Hello,

I'm adding Thaumcraft recipe integration to [JEI](https://github.com/mezz/JustEnoughItems) Addons for Minecraft 1.8.
I want to hide recipes that are not researched, but it's difficult to efficiently determine when research has happened.

Can you fire a `ResearchComplete` event after `PacketResearchComplete.processMessage` and a `ResearchSync` event after `PacketSyncResearch.onMessage`?

**Comment by Azanor** [comment]
Do you really need an event? Research is synced clientside so all you need to do is call ResearchHelper.isResearchComplete to determine if a recipe should be displayed or not.

**Comment by mezz** [comment]
I normally load the recipes at the `FMLModIdMappingEvent` which is before the research has been synchronized (first done at `PlayerEvent.PlayerLoggedInEvent`). I would like to have the recipes ready as soon as the research is synchronized, but there's no reliable way to know that has happened without polling and waiting in a loop. If I check during `PlayerEvent.PlayerLoggedInEvent` for instance, the research sync packet is not guaranteed to have reached the client yet.

The other event, `ResearchComplete` is important to keep the recipes up to date without having to check each recipe many times, which I have to avoid in order to keep the UI responsive. Currently I'm listening for the "thaumcraft:learn" sound event, which is a scary thing to rely on.

**Comment by Azanor** [comment]
Do you still require this event or did you find another way to go about it?

**Comment by mezz** [comment]
I looked into it more and I still require the events.

**Comment by mezz** [comment]
I decided to go about this a different way, and just show all recipes and mark the ones that are not researched.

**Comment by Azanor** [comment]
Sorry, I kept meaning to work on this (and forgetting).

**Comment by mezz** [comment]
Not a problem, the way I was doing it before was a bit too complicated anyway. I think this works better.
