### ISSUE TITLE
Suggestion: IRepairable or IRepairableExtended canApplyRepairEnchant method addition

### ISSUE THREAD

**Issue by ColinGBos** [Azanor/thaumcraft-5-api#7]
I have an item which I would like to be able to have the Repair enchant, but it has nbt variants that I don't want to be able to have the Repair enchant. As far as I know your repair enchantment just checks for instanceof IRepairable for it's canApply method currently and that would change to something like:
instanceof IRepairable && canApplyRepairEnchant;

**Comment by ColinGBos** [comment]
Any comment on something like this @Azanor or is what I am trying to do what IRepairableExtended is for?

**Comment by Azanor** [comment]
Yup, use IRepairableExtended to check the nbt.

**Comment by ColinGBos** [comment]
After some testing, even when returning false from doRepair, "repair" still has the ability to be placed on the item. It appears that the effect of returning false here is just to prevent the item from actually being repaired.
The reason I bring this up so persistently is because I have an hammer item, which uses a single item id, but has the material stored in an nbt tag, I include a thaumium hammer which I want to be able to be repaired, but there is no way for me to make sure that none of the other items can get the repair enchant, which means iron, gold and diamond hammers all end up getting repair on them.
