### ISSUE TITLE
 Thaumium fortress armor + Googles of revealing not working'

### ISSUE THREAD

**Issue by gmunaro** [Azanor/thaumcraft-5-api#9]
The infusion recipe is probably wrong, because i cant craft it.

**Comment by Azanor** [comment]
Are you using a fresh, undamaged pair of goggles and armor?
BTW, This is the wrong place to report the error.

**Comment by gmunaro** [comment]
1) Accordingly the thaumominicon animation, the helm and the googles can have any damage value. The weird thing is that the crafting is requiring the helmet with the googles in the middle pedestal in order to create a helmet with googles; insted of requiring just a normal helmet. 
2) I'm sorry, i didn't knew that this area wasn't for this kind of error reporting, i'm sorry, Azanor.
3) Love your work!
4) Here's a screenshot: https://drive.google.com/file/d/0B6CV80CAPqddVGVnNEhpbHdDUzA/view?usp=sharing
